In [40]:
import numpy as np
def insertion_sort(alist):
    for i in range(0, len(alist)):
        j = i-1
        while alist[j+1] < alist[j] and j>=0:
            alist[j], alist[j+1] = alist[j+1], alist[j]
            j = j - 1
    return alist
        
                
            
        

In [38]:
insertion_sort([3,5,93,1,4])

[1, 3, 4, 5, 93]

In [39]:
assert [1, 3, 8, 10] == insertion_sort([8,3,10,1])

In [89]:
for i in range(5):
    rnd = np.random.randint(1,50,14)
    unsorted = rnd.copy()
    rnd.sort()
    print unsorted
    assert rnd.all() == insertion_sort(unsorted).all()
    #print insertion_sort(unsorted), unsorted
    

[45 32 43 24 35 13 47 24 10 46  1 38 47  7]
[28 35 35 26 10 11 28 42 15 30 43  5 49 31]
[37 40 11  8 17 29 31 21 46 12 13 23 47  4]
[42 26 33 23 17 26 12 21 11 45 23 27 14  3]
[11 26 42 22 11 13  2 35 11 32 49 45 21 26]


In [83]:
rnd = np.random.randint(1,10,4)

In [75]:
%timeit insertion_sort(rnd)

The slowest run took 10.13 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.82 µs per loop
